### ISSUE TITLE
TODO とか MEMO とか 進捗とか

### ISSUE THREAD

**Issue by tacigar** [tacigar/maidroid#15]
- [ ] `maidroid/maidroid`
  - [x] maidroidに名前を持たせる(nametag)
  - [x] maidroidの状態をinfotextで表示
  - [ ] maidroidにアイテムを持たせる処理
- [ ] `maidroid/maidroid_core`
  - [ ] 昔実装してたやつはもうちょっと賢くして実装しなおす
    - [x] empty
    - [x] basic(旧player_chasing)
    - [ ] `minetest.find_path` の使い方を調べる
    - [ ] farming
    - [ ] lumberjack
  - [ ] ほかにも役立ちそうなやつを実装しよう
    - [ ] 暗ければ明るく照らしてくれる系
    - [ ] Guard Maidroid (Core)
- [ ] `maidroid/maidroid_tool`
  - [x] core writerの実装
    - [x] active core writerの実装
    - [x] inactive core writerの実装
    - [x] core writerの上で回るcoreの実装
    - [x] core_writerのformspecをいい感じにしなければならない
  - [ ] maidroidを作る機械の実装（名前も決める必要がある）
- [ ] `README.md`
  - [ ] maidroid MODの概要
  - [ ] 各アイテムの使い方
  - [ ] 各アイテムのレシピ
  - [ ] APIの簡単な説明

**Comment by tacigar** [comment]
今のはあまりに粗末なので探索のアルゴリズムをもうちょっと本格的なのに変えた方がいいと思う。
候補としては、
- A\* Algorithm
- グリーディ（ダイクストラ）でパワー系
- Concurrent ダイクストラなるもの（よく知らない）

まあ普通に考えればA*だと思う。
ただ、周りのノードの高さのマップを得るのが Minetest の提供する API 的に難しい気がする。

**Comment by tacigar** [comment]
プレーヤーを追う core に関しては妙にアルゴリズム使うよりはガバガバ実装の方がそれっぽさがでると思う。

**Comment by ghost** [comment]
探索ならfind_pathを使ってみてはいかがでしょう。
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L2238

**Comment by ghost** [comment]
maidroid.maidroid.set_yaw_by_directionはautomatic_face_movement_dirで代用できます。
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L3468

**Comment by tacigar** [comment]
> 探索ならfind_pathを使ってみてはいかがでしょう。

わお！こんなのも提供されていたんですね！すごい…。
使わせていただきます！

> maidroid.maidroid.set_yaw_by_directionはautomatic_face_movement_dirで代用できます。

なるほど。Objectのプロパティにそんなのがあったんですね。知らなかった…。
情報ありがとうございます！使わせていただきます！

**Comment by ghost** [comment]
maidroid.maidroid.get_nearest_player内のmin_distance変数は一切更新されませんが、仕様でしょうか。(range_distanceと同じ値を取り続けます)
このままだとプレイヤーの優先順位が不定な気がします。

**Comment by tacigar** [comment]
うわ、ほんとですね…。
ありがとうございます。

**Comment by tacigar** [comment]
![formspec](https://cloud.githubusercontent.com/assets/19551419/18572497/f368a13e-7bf6-11e6-9d6f-3792927aca2c.gif)
formspecがそれっぽい感じになった。
